
[font]
size = 15

[font.normal]
family = "MesloLGM Nerd Font"
style = "regular"

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.600000

[window.padding]
x = 30
y = 30

[general]
# Theme/colorscheme importing
import = [
    "~/.config/alacritty/themes/themes/ashen.toml",
]

[terminal]
